Add stdout back for next steps in workflow

diff --git a/.github/workflows/disseminate.yml b/.github/workflows/disseminate.yml
--- a/.github/workflows/disseminate.yml
+++ b/.github/workflows/disseminate.yml
@@ -57,16 +57,19 @@ jobs:
           workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_ID_PROVIDER }}
           service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
 
-      - name: Run disseminator and save summary
+      - name: Run disseminator and save outputs
         run: |
           set -o pipefail
-          OUTPUT=$(python disseminator.py \
+          python disseminator.py \
             --work ${{ inputs.work-id }} \
-            --platform ${{ inputs.platform }} 2>&1) || STATUS=$?
-          echo "### Dissemination Output" >> $GITHUB_STEP_SUMMARY
-          echo '```' >> $GITHUB_STEP_SUMMARY
-          echo "$OUTPUT" >> $GITHUB_STEP_SUMMARY
-          echo '```' >> $GITHUB_STEP_SUMMARY
+            --platform ${{ inputs.platform }} > ${{ inputs.work-id }} 2> /tmp/error.log || STATUS=$?
+          ERROR_LOG=$(cat /tmp/error.log)
+          if [ -n "$ERROR_LOG" ]; then
+            echo "### Dissemination Errors" >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+            echo "$ERROR_LOG" >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+          fi
           exit ${STATUS:-0}
 
       - name: Upload output to artifact
